"""HTML UI builder functions."""


def _wrap_html_page(title: str, body_html: str, extra_head: str = "") -> str:
    return (
        "<!DOCTYPE html>"
        "<html lang=\"en\">"
        "<head>"
        "  <meta charset=\"utf-8\" />"
        "  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\" />"
        f"  <title>{title}</title>"
        f"  {extra_head}"
        "  <style>"
        "    body { font-family: system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; margin: 0; padding: 0; background: #f7f7f7; color: #111; }"
        "    .container { max-width: 900px; margin: 0 auto; padding: 32px 24px; }"
        "    h1 { margin-top: 0; }"
        "    h2 { margin-bottom: 0.5em; }"
        "    p { line-height: 1.6; }"
        "    pre { background: #111; color: #eee; padding: 14px; overflow-x: auto; border-radius: 6px; }"
        "    code { font-family: ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, 'Liberation Mono', 'Courier New', monospace; }"
        "    a { color: #1a73e8; }"
        "    table { border-collapse: collapse; width: 100%; margin-top: 1em; }"
        "    th, td { text-align: left; padding: 10px; border-bottom: 1px solid #ddd; }"
        "    th { background: #f4f6f8; }"
        "  </style>"
        "</head>"
        "<body>"
        "  <div class=\"container\">"
        f"{body_html}"
        "  </div>"
        "</body>"
        "</html>"
    )


def build_api_info_page() -> str:
    body = (
        "<h1>Bible API</h1>"
        "<p>This API exposes Bible passages and metadata for a set of translations. It is designed to be easy to call from scripts, web clients, or other services.</p>"
        "<p>To use the interactive explorer, visit <a href=\"/\">/</a>.</p>"
        "<h2>Endpoints</h2>"
        "<ul>"
        "<li><strong>/</strong> - Interactive passage explorer UI.</li>"
        "<li><strong>/passage</strong> - Retrieve a passage for a translation (JSON).</li>"
        "<li><strong>/translations</strong> - JSON list of available translations.</li>"
        "<li><strong>/translations/{abbreviation}</strong> - Metadata for a specific translation.</li>"
        "<li><strong>/translations-info</strong> - HTML summary of available translations (with links).</li>"
        "</ul>"
        "<h2>Examples</h2>"
        "<p>Fetch a passage in the Lexham English Bible (LEB):</p>"
        "<pre><code>GET /passage?ref=John+3:16&translation=LEB</code></pre>"
        "<p>List available translations (JSON):</p>"
        "<pre><code>GET /translations</code></pre>"
        "<p>Translation details (HTML):</p>"
        "<pre><code>GET /translations-info</code></pre>"
    )
    return _wrap_html_page("Bible API", body)


def build_translations_ui_page() -> str:
    body = (
        "<h1>Bible Passage Explorer</h1>"
        "<p>Use this page to look up passages quickly across translations.</p>"
        "<div class=\"controls\">"
        "  <input type=\"text\" id=\"ref\" value=\"Matthew 4:1-11\" placeholder=\"e.g. Matthew 4:1-11\" />"
        "  <select id=\"translation\"></select>"
        "  <label style=\"display:flex;align-items:center;gap:5px;font-size:14px;cursor:pointer;\" title=\"Only available for Psalms\">"
        "    <input type=\"checkbox\" id=\"psalter\" disabled /> Scottish Psalter"
        "  </label>"
        "  <button id=\"searchBtn\">Search</button>"
        "</div>"
        "<div id=\"tabs\" class=\"tabs\">"
        "  <div class=\"tab active\" data-tab=\"passage\">Passage</div>"
        "  <div class=\"tab\" data-tab=\"about\">About</div>"
        "  <div class=\"tab\" data-tab=\"copyright\">Copyright</div>"
        "  <button id=\"copyBtn\" class=\"copy-btn\" disabled>Copy HTML</button>"
        "</div>"
        "<div id=\"output\" class=\"text-html text-indent\">"
        "  <p style=\"color: grey;\">Results will appear here...</p>"
        "</div>"
        "<div id=\"metadata-content\" class=\"text-html\" style=\"display:none;\"></div>"
        "<style>"
        "  .controls{display:flex;gap:15px;margin-bottom:20px;align-items:center;}"
        "  .controls input[type=\"text\"]{flex:1;padding:10px;font-size:16px;}"
        "  .controls select, .controls button{padding:10px;font-size:16px;}"
        "  .tabs{display:flex;border-bottom:2px solid #eee;margin-bottom:20px;align-items:center;}"
        "  .tab{padding:10px 20px;cursor:pointer;border:1px solid transparent;border-bottom:none;margin-bottom:-2px;font-weight:bold;color:#666;}"
        "  .tab.active{color:#007bff;border-color:#eee;border-top:3px solid #007bff;background:#fff;border-radius:4px 4px 0 0;}"
        "  .tab:hover:not(.active){background:#f0f0f0;}"
        "  .copy-btn{margin-left:auto;padding:10px 14px;font-size:14px;border:1px solid #ddd;border-radius:5px;background:#fafafa;cursor:pointer;}"
        "  .copy-btn:disabled{opacity:.55;cursor:not-allowed;}"
        "</style>"
        "<script>"
        "  const state = { currentTab: 'passage' };"
        "  function updatePsalterCheckbox(){"
        "    const ref = document.getElementById('ref').value;"
        "    const psalterCb = document.getElementById('psalter');"
        "    const isPsalms = /psalm|ps\\./i.test(ref);"
        "    psalterCb.disabled = !isPsalms;"
        "    if(!isPsalms) psalterCb.checked = false;"
        "  }"
        "  async function loadTranslations(){"
        "    const select = document.getElementById('translation');"
        "    select.innerHTML = '<option>Loading...</option>';"
        "    try{"
        "      const res = await fetch('/translations');"
        "      if(!res.ok){"
        "        throw new Error(`HTTP ${res.status} ${res.statusText}`);"
        "      }"
        "      const data = await res.json();"
        "      if(!Array.isArray(data.translations)) throw new Error('Invalid translations response');"
        "      select.innerHTML = data.translations.map(t=>{"
        "        const abbr = t.abbreviation;"
        "        const full = t.full_name || '';"
        "        const hasSuffix = full.toUpperCase().endsWith(` (${abbr.toUpperCase()})`);"
        "        const display = full ? (hasSuffix ? full : `${full} (${abbr})`) : abbr;"
        "        return `<option value=\"${abbr}\">${display}</option>`;"
        "      }).join('');"
        "    }catch(err){"
        "      select.innerHTML = `<option value=\"\">Failed to load (${err.message})</option>`;"
        "    }"
        "  }"
        "  async function fetchMetadata(tab){"
        "    const select = document.getElementById('translation');"
        "    const translation = select.value;"
        "    const meta = document.getElementById('metadata-content');"
        "    const displayName = select.options[select.selectedIndex]?.text || translation;"
        "    meta.innerHTML = '<p>Loading...</p>';"
        "    try{"
        "      const res = await fetch(`/translations/${encodeURIComponent(translation)}`);"
        "      const data = await res.json();"
        "      if(data.error){ meta.innerHTML = `<p style=\"color:red;\">${data.error}</p>`; return; }"
        "      const publisher = data.publisher_url ? `<a href=\"${data.publisher_url}\" target=\"_blank\">${data.publisher_name}</a>` : (data.publisher_name || '');"
        "      let content = `<div style=\"margin-bottom:20px;padding-bottom:10px;border-bottom:1px solid #ddd;\"><strong>Publisher:</strong> ${publisher}</div>`;"
        "      if(tab==='about') content += `<h2>About ${displayName}</h2>${data.about_html||'<p>None.</p>'}`;"
        "      if(tab==='copyright') content += `<h2>Copyright ${displayName}</h2>${data.copyright_html||'<p>None.</p>'}`;"
        "      meta.innerHTML = content;"
        "    }catch(err){ meta.innerHTML = `<p style=\"color:red;\">Network Error: ${err.message}</p>`; }"
        "  }"
        "  async function fetchPassage(){"
        "    switchTab('passage');"
        "    const ref = document.getElementById('ref').value;"
        "    const translation = document.getElementById('translation').value;"
        "    const psalter = document.getElementById('psalter').checked;"
        "    const output = document.getElementById('output');"
        "    const copyBtn = document.getElementById('copyBtn');"
        "    output.innerHTML = '<p>Loading...</p>';"
        "    copyBtn.disabled = true;"
        "    try{"
        "      const url = `/passage?ref=${encodeURIComponent(ref)}&translation=${encodeURIComponent(translation)}${psalter ? '&psalter=true' : ''}`;"
        "      const res = await fetch(url);"
        "      const data = await res.json();"
        "      if(data.error){"
        "        output.innerHTML = `<p style=\"color:red;\">${data.error}</p>`;"
        "      } else {"
        "        output.innerHTML = `<div class=\"passage-box\">${data.html}</div>`;"
        "        copyBtn.disabled = false;"
        "      }"
        "    }catch(err){ output.innerHTML = `<p style=\"color:red;\">Network Error: ${err.message}</p>`; }"
        "  }"
        "  function switchTab(tab){"
        "    state.currentTab = tab;"
        "    document.querySelectorAll('.tab').forEach(t=>t.classList.toggle('active', t.dataset.tab===tab));"
        "    document.getElementById('output').style.display = tab==='passage' ? 'block' : 'none';"
        "    document.getElementById('metadata-content').style.display = tab==='passage' ? 'none' : 'block';"
        "    if(tab!=='passage') fetchMetadata(tab);"
        "  }"
        "  document.addEventListener('DOMContentLoaded', ()=>{"
        "    loadTranslations();"
        "    const refInput = document.getElementById('ref');"
        "    refInput.addEventListener('input', updatePsalterCheckbox);"
        "    updatePsalterCheckbox();"
        "    const copyBtn = document.getElementById('copyBtn');"
        "    copyBtn.addEventListener('click', async ()=>{"
        "      const output = document.getElementById('output');"
        "      const passage = output.querySelector('.passage-box');"
        "      if(!passage) return;"
        "      try{"
        "        await navigator.clipboard.writeText(passage.innerHTML);"
        "        alert('Passage HTML copied to clipboard.');"
        "      }catch(e){"
        "        alert('Copy failed: '+e.message);"
        "      }"
        "    });"
        "    document.getElementById('searchBtn').addEventListener('click', fetchPassage);"
        "    document.querySelectorAll('.tab').forEach(t=>t.addEventListener('click', ()=>switchTab(t.dataset.tab)));"
        "  });"
        "</script>"

    )

    extra_head = (
        "<link rel=\"stylesheet\" href=\"/static/base.css\">"
        "<link rel=\"stylesheet\" href=\"/static/passage-text.css\">"
    )
    return _wrap_html_page("Bible Explorer", body, extra_head=extra_head)
